options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "python"
    entrypoint: "python"
    args: ['-m', 'pip', 'install', '--upgrade', 'pip']

  
  - name: 'python'
    entrypoint: 'bash'
    args: ['-c', 'apt-get update && apt-get install -y make']

  - name: 'python'
    entrypoint: 'make'
    args: ['install', 'lint',]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['app', 'deploy', '--quiet']