options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "python"
    entrypoint: "python"
    args: ['-m', 'pip', 'install', '--upgrade', 'pip']

  
  - name: 'python'
    entrypoint: 'bash'
    args: ['-c', 'apt-get update && apt-get install -y make']

  - name: 'python'
    entrypoint: 'make'
    args: ['install', 'lint',]

  # This step will build and push new container image to "google container registry(GCR)"
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/fnote-taking', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/fnote-taking']

  # This step will deploy the new container image to cloud run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run','deploy', 'fnote-taking-service', '--image=gcr.io/$PROJECT_ID/fnote-taking', '--region=us-west4', '--allow-unauthenticated']
