options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: "python"
  entrypoint: "python"
  args: ['-m', 'pip', 'install', '--upgrade', 'pip']


- name: 'python'
  entrypoint: 'bash'
  args: ['-c', 'apt-get update && apt-get install -y make']

- name: 'python'
  entrypoint: 'make'
  args: ['install', 'lint',]

# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/bostenappproject/my-repo/bostenapp/bostenapp-service:$COMMIT_SHA', '.']

# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/bostenappproject/my-repo/bostenapp/bostenapp-service:$COMMIT_SHA']

# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
    - 'run'
    - 'deploy'
    - 'bostenapp-service'
    - '--image'
    - 'us-central1-docker.pkg.dev/bostenappproject/my-repo/bostenapp/bostenapp-service:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/bostenappproject/my-repo/bostenapp/bostenapp-service:$COMMIT_SHA'

